# This is a basic workflow to help you get started with Actions

name: Build React on lightsail

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master  # リポジトリをチェックアウト

      - name: Install AWS Client
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Install Dependencies
        run: npm install

      - name: Build React application
        run: npm run build  # React ビルド

      - name: Build Docker Image
        run: |
          docker build -t ctf-recipe:latest -f dockerfile.deploy .

      - name: push and Deploy
        run: |
          service_name=container-service-1
          aws lightsail push-container-image \
            --region ap-northeast-1 \
            --service-name ${service_name} \
            --label web \
            --image ctf-recipe:latest
